# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='peliculas/static/img/actores')),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='peliculas/static/img/directores')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bandera', models.ImageField(upload_to='peliculas/static/img/banderas')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caratula', models.ImageField(upload_to='peliculas/static/img/caratulas')),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('psinosis', models.TextField()),
                ('clasificacion', models.IntegerField()),
                ('actores', models.ManyToManyField(to='peliculas.Actores')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Directores')),
                ('genero', models.ManyToManyField(to='peliculas.Generos')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Paises')),
            ],
        ),
        migrations.CreateModel(
            name='Productoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='peliculas/static/img/productoras')),
            ],
        ),
        migrations.AddField(
            model_name='peliculas',
            name='productora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Productoras'),
        ),
        migrations.AddField(
            model_name='directores',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Paises'),
        ),
        migrations.AddField(
            model_name='actores',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Paises'),
        ),
    ]
