# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_auto_20160516_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='caratula',
            field=models.ImageField(upload_to='static/img/caratulas'),
        ),
    ]
