# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_auto_20160516_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 14, 35, 16, 524048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='caratula',
            field=models.ImageField(upload_to='static/img/caratulas'),
        ),
    ]
