# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_auto_20160519_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='psinosis',
            new_name='sinopsis',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 17, 36, 52, 607398, tzinfo=utc)),
        ),
    ]
