# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_auto_20160602_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 13, 6, 54, 847536, tzinfo=utc)),
        ),
    ]
