# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='anonimus.jpg', null=True, upload_to='profiles'),
        ),
    ]
